### PR TITLE
Add Linters and made changes to html and css

### PR DESCRIPTION
**Pull request by fibini**
Added Linters and fixed the errors to index.html and css files for code review

### CODE REVIEW

**Review by fibini — COMMENTED** [review]
Good job having no linter errors , good commit message :+1: and used the correct flow. I suggest adding a sections tag `<section></section>` to span lines 28 and 75 would make it more semantic :smile:  . I can also suggest you try using display : flex on the container to help with styling.

**Review by koomekevo — CHANGES_REQUESTED** [review]
Hi @fibini, 



Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly use Github inline comments to highlight the file and line of code where the student needs to make a change as shown below. 

github-inline-comments

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fibini** [comment]
Had to make the inline comments to the commits, it was not allowing me to make inline comments exactly on the line i wanted to start from in the (Files changed) section

**Review by Munsa1 — APPROVED** [review]
## Status Approved

Hi @fibini 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
